# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitter Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter Clone
  #pod 'Firebase/Core'
  #pod 'Firebase/Auth'
  #pod 'Firebase/Database'
  #pod 'Firebase/Storage'

  target 'Twitter CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Twitter CloneUITests' do
    # Pods for testing
  end

end
